version: "3"
services:
  client:
    image: "anishsinha1/complex-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "anishsinha1/complex-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PG_USER=${PG_USER}
      - PG_HOST=${PG_HOST}
      - PG_DATABASE=${PG_DATABASE}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
  worker:
    image: "anishsinha1/complex-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
  nginx:
    image: "anishsinha1/complex-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
